FROM nginxinc/nginx-unprivileged:1.31.4-alpine
ARG UID=101
LABEL maintainer="Custom Thai Shlink Web Client"

USER root
RUN rm -r /usr/share/nginx/html && rm /etc/nginx/conf.d/default.conf
COPY config/docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY scripts/docker/servers_from_env.sh /docker-entrypoint.d/30-shlink-servers-json.sh
COPY build /usr/share/nginx/html

RUN echo '[]' > /usr/share/nginx/html/servers.json \
    && chown $UID:0 /usr/share/nginx/html/servers.json

USER $UID
